      SUBROUTINE FILL0(BITMAP, N)                                       
!
!     FILL THE FIRST N BITS OF BITMAP WITH ZEROES.
!
      INTEGER BITMAP(1), N
!
      DATA NBPW /35/
!     NBPW IS THE MINIMUM NUMBER OF SIGNIFICANT BITS PER WORD USED
!     BY INTEGER ARITHMETIC.  THIS IS USUALLY ONE LESS THAN THE
!     ACTUAL NUMBER OF BITS PER WORD, BUT AN IMPORTANT EXCEPTION IS
!     THE CDC-6000 SERIES OF MACHINES, WHERE NBPW SHOULD BE 48.
!
      LOOP = N/NBPW
      NBLW = MOD(N,NBPW)
      IF (LOOP.EQ.0) GO TO 20
      DO 10 I=1,LOOP
        BITMAP(I) = 0
   10 CONTINUE
   20 IF (NBLW.NE.0) BITMAP(LOOP+1) = MOD(BITMAP(LOOP+1),2**(NBPW-NBLW) &
        )
      RETURN
      END
